### ISSUE TITLE
Something Cool

### ISSUE THREAD

**Issue by mr-desilva** [bmorashad/bmorashad.github.io#1]
Bro nice work 👏, just a suggestion that if you can add something like **"View Live"** option for projects. 
Eg: - Genimen is still live from the client side.
Link - https://genimen.netlify.app/home

**Comment by bmorashad** [comment]
Thanks man :)
Yah that wd be  great dude, but the reason why I didn't add such an option is bc the Genimen backend is not running ATM :(, it's just the frontend as u said and the _user will be stuck at login screen_....

Im hoping to host the backend back and once I do, will add a **View Live** option 😃

**Comment by mr-desilva** [comment]
Great bro  (●'◡'●)
